{% set name = "lifelines" %}

{% set version = "0.21.4" %}
{% set sha256 = "a49ab47112d30c3739f3fa57b93256f7e40d4a20836cdd6da8e7a00e8b93363f" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CamDavidsonPilon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5
    - pip

  run:
    - python >=3.5
    - setuptools
    - numpy >=1.14.0
    - scipy <=1.2.1, >=1.0
    - pandas >=0.23.0
    - matplotlib >=3.0
    - autograd >=1.2
    - bottleneck >=1.0

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils

about:
  home: https://github.com/CamDavidsonPilon/lifelines
  license: MIT
  license_file: LICENSE
  summary: 'Survival analysis in Python, including Kaplan Meier, Nelson Aalen and regression'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
