{% set name = "lifelines" %}


{% set version = "0.29.0" %}
{% set sha256 = "270c0c651549ab21a9bf5d214046ff2cef0749d40fb5eaa88a4d45e0585fced5" %}



package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CamDavidsonPilon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip

  run:
    - python >=3.9
    - setuptools
    - numpy >=1.14.0
    - scipy >=1.2
    - pandas >=1.2.0
    - matplotlib-base >=3.0
    - autograd >=1.5
    - autograd-gamma >=0.3
    - formulaic >=0.2.2

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils

about:
  home: https://github.com/CamDavidsonPilon/lifelines
  license: MIT
  license_file: LICENSE
  summary: Survival analysis in Python, including Kaplan Meier, Nelson Aalen and regression

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
