{% set name = "lifelines" %}


{% set version = "0.25.8" %}
{% set sha256 = "2aef2026b36ea897d343efcd507ae4cc7ea66eb7087cff3897239b8560f6c643" %}



package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CamDavidsonPilon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - setuptools
    - numpy >=1.14.0
    - scipy >=1.2
    - pandas >=0.23.0
    - matplotlib-base >=3.0
    - autograd >=1.3
    - autograd-gamma >=0.3
    - formulaic >=0.2.0

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils

about:
  home: https://github.com/CamDavidsonPilon/lifelines
  license: MIT
  license_file: LICENSE
  summary: Survival analysis in Python, including Kaplan Meier, Nelson Aalen and regression

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
